import sindhu from "../assets/rumkit.jpg";

export const dataModules = [
  {
    title: "Rumkit Dik Pusdikkes ",
    img: "https://i.imgur.com/MHsMNEd.jpeg",
    link: import.meta.env.VITE_PUSDIKES,
    satuan: "Pusdikkes",
  },
  {
    title: "Rumkit Tk.II Iskandar Muda, Banda Aceh",
    img: "https://i.imgur.com/SV6uBDY.jpeg",
    link: import.meta.env.VITE_ISKANDAR,
    satuan: "Kesdam IM",
  },
  {
    title: "Rumkit Tk.IV Lhokseumawe",
    img: "https://i.imgur.com/ZKfV8DG.jpeg",
    link: import.meta.env.VITE_LHOKSEUMAWE,
    satuan: "Kesdam IM",
  },
  {
    title: "Rumkit Tk.IV Meulaboh",
    img: "",
    link: "#",
    satuan: "Kesdam IM",
  },
  {
    title: "Rumkit Tk.II Putri Hijau, Medan",
    img: "https://i.imgur.com/ML608FL.jpeg",
    link: import.meta.env.VITE_PUTRI_HIJAU,
    satuan: "Kesdam I/BB",
  },
  {
    title: "Rumkit Tk.III dr. Reksodiwiryo, Padang",
    img: "https://i.imgur.com/p5cP9fs.jpeg",
    link: "#",
    satuan: "Kesdam I/BB",
  },
  {
    title: "Rumkit Tk.IV Pematang Siantar",
    img: "https://i.imgur.com/mjYNQPz.jpeg",
    link: import.meta.env.VITE_PEMATANGSIANTAR,
    satuan: "Kesdam I/BB",
  },
  {
    title: "Rumkit Tk.IV Padang Sidempuan",
    img: "https://i.imgur.com/ONutlU8.jpeg",
    link: "#",
    satuan: "Kesdam I/BB",
  },
  {
    title: "Rumkit Tk.IV Bukit Tinggi",
    img: "https://i.imgur.com/Maqt8vG.jpeg",
    link: "#",
    satuan: "Kesdam I/BB",
  },
  {
    title: "Rumkit Tk.IV Pekan Baru",
    img: "",
    link: "#",
    satuan: "Kesdam I/BB",
  },
  {
    title: "Rumkit Tk.IV Binjai",
    img: "https://i.imgur.com/x3urLY2.jpeg",
    link: "#",
    satuan: "Kesdam I/BB",
  },
  {
    title: "Rumkit Tk.IV Solok",
    img: "https://i.imgur.com/ilfLjf4.jpeg",
    link: import.meta.env.VITE_SOLOK,
    satuan: "Kesdam I/BB",
  },
  {
    title: "Rumkit Tk.II dr. A K Gani, Palembang",
    img: "https://i.imgur.com/RtIxyYC.jpeg",
    link: import.meta.env.VITE_AKGANI,
    satuan: "Kesdam II/SWJ",
  },
  {
    title: "Rumkit Tk.III Bratanata, Jambi",
    img: "https://i.imgur.com/Ma7ls9q.jpeg",
    link: import.meta.env.VITE_BRATANATA,
    satuan: "Kesdam II/SWJ",
  },
  {
    title: "Rumkit Tk.III dr. Noesmir, Baturaja",
    img: "https://i.imgur.com/MsGyvmq.jpeg",
    link: import.meta.env.VITE_NOESMIR,
    satuan: "Kesdam II/SWJ",
  },
  {
    title: "Rumkit Tk.IV Lahat",
    img: "https://i.imgur.com/xG3JlUp.jpeg",
    link: "#",
    satuan: "Kesdam II/SWJ",
  },
  {
    title: "Rumkit Tk.IV Bengkulu",
    img: "https://i.imgur.com/AvCp3Zi.jpeg",
    link: import.meta.env.VITE_BENGKULU,
    satuan: "Kesdam II/SWJ",
  },
  {
    title: "Rumkit Tk. IV/Bandar Lampung",
    img: "https://i.imgur.com/d6bdcDo.jpeg",
    link: "#",
    satuan: "Kesdam II/SWJ",
  },
  {
    title: "Rumkit Tk.IV Batin Tikal Pangkal Pinang",
    img: "https://i.imgur.com/vtzQNLG.jpeg",
    link: "#",
    satuan: "Kesdam II/SWJ",
  },
  {
    title: "Rumkit Tk.II Dustira, Cimahi",
    img: "https://i.imgur.com/4pjuzBJs.jpeg",
    link: import.meta.env.VITE_DUSTIRA,
    satuan: "Kesdam III/Slw",
  },
  {
    title: "Rumkit Tk. III Ciremai, Cirebon",
    img: "https://i.imgur.com/tuzUYeG.jpeg",
    link: import.meta.env.VITE_CIREMAI,
    satuan: "Kesdam III/Slw",
  },
  {
    title: "Rumkit Tk.III Salak, Bogor",
    img: "https://i.imgur.com/klD3gpq.jpeg",
    link: import.meta.env.VITE_SALAK,
    satuan: "Kesdam III/Slw",
  },
  {
    title: "Rumkit Tk.IV Kencana, Serang",
    img: "https://i.imgur.com/8FCZfyw.jpeg",
    link: import.meta.env.VITE_KENCANA,
    satuan: "Kesdam III/Slw",
  },
  {
    title: "Rumkit Tk.IV Sariningsih, Bandung",
    img: "https://i.imgur.com/9mLYGxb.jpeg",
    link: import.meta.env.VITE_SARININGSIH,
    satuan: "Kesdam III/Slw",
  },
  {
    title: "Rumkit Tk.IV Guntur, Garut",
    img: "https://i.imgur.com/Ke4pmXv.jpeg",
    link: import.meta.env.VITE_GUNTUR,
    satuan: "Kesdam III/Slw",
  },
  {
    title: "Rumkit Tk. II dr. Soedjono, Magelang",
    img: "https://i.imgur.com/JX9Sg6i.jpeg",
    link: "#",
    satuan: "Kesdam IV/Dip",
  },
  {
    title: "Rumkit Tk.III Wijaya Kusuma, Purwokerto",
    img: "https://i.imgur.com/ptBUUWZ.jpeg",
    link: import.meta.env.VITE_WIJAYA,
    satuan: "Kesdam IV/Dip",
  },
  {
    title: "Rumkit Tk.III Bhakti Wira Tamtama, Semarang",
    img: "https://i.imgur.com/BuJgtYQ.jpeg",
    link: "#",
    satuan: "Kesdam IV/Dip",
  },
  {
    title: "Rumkit Tk.III dr. Soetarto Yogyakarta",
    img: "https://i.imgur.com/WG8yGct.jpeg",
    link: import.meta.env.VITE_SOETARTO,
    satuan: "Kesdam IV/Dip",
  },
  {
    title: "Rumkit Tk.III Slamet Riyadi Surakarta",
    img: "https://i.imgur.com/6jtKRLu.jpeg",
    link: import.meta.env.VITE_SLAMET,
    satuan: "Kesdam IV/Dip",
  },
  {
    title: "Rumkit Tk.IV Tegal",
    img: "https://i.imgur.com/bGRQ6As.jpeg",
    link: import.meta.env.VITE_RUMKITTEGAL,
    satuan: "Kesdam IV/Dip",
  },
  {
    title: "Rumkit Tk.IV dr. Asmir Salatiga",
    img: "https://i.imgur.com/pocxEx3.jpeg",
    link: import.meta.env.VITE_ASMIR,
    satuan: "Kesdam IV/Dip",
  },
  {
    title: "Rumkitban Kudus",
    img: "",
    link: "#",
    satuan: "Kesdam IV/Dip",
  },
  {
    title: "Rumkitban Blora",
    img: "https://i.imgur.com/bMKYBlB.jpeg",
    link: "#",
    satuan: "Kesdam IV/Dip",
  },
  {
    title: "Rumkit Tk.II Soepraoen, Malang",
    img: "https://i.imgur.com/TYyik11.jpeg",
    link: import.meta.env.VITE_SOAPROEN,
    satuan: "Kesdam V/Brw",
  },
  {
    title: "Rumkit Tk.III Brawijaya, Surabaya",
    img: "https://i.imgur.com/KVfzBXk.jpeg",
    link: import.meta.env.VITE_BRAWIJAYA,
    satuan: "Kesdam V/Brw",
  },
  {
    title: "Rumkit Tk.III Baladika Husada, Jember",
    img: "https://i.imgur.com/yS2lSwZ.jpeg",
    link: import.meta.env.VITE_BALADHIKA,
    satuan: "Kesdam V/Brw",
  },
  {
    title: "Rumkit Tk.IV Madiun",
    img: "",
    link: "#",
    satuan: "Kesdam V/Brw",
  },
  {
    title: "Rumkit Tk. IV/Kediri",
    img: "",
    link: "#",
    satuan: "Kesdam V/Brw",
  },
  {
    title: "Rumkitban Bhirawa Bhakti Malang",
    img: "",
    link: "#",
    satuan: "Kesdam V/Brw",
  },
  {
    title: "Rumkitban Lawang",
    img: "",
    link: "#",
    satuan: "Kesdam V/Brw",
  },
  {
    title: "Rumkitban Sidoarjo",
    img: "https://i.imgur.com/wgYuccc.jpeg",
    link: "#",
    satuan: "Kesdam V/Brw",
  },
  {
    title: "Rumkitban Surabaya",
    img: "https://i.imgur.com/KGMF8HT.jpeg",
    link: import.meta.env.VITE_BANSURABAYA,
    satuan: "Kesdam V/Brw",
  },
  {
    title: "Rumkit Tk.II dr. Hardjanto Balikpapan",
    img: "https://i.imgur.com/C21m4Vd.jpeg",
    link: "#",
    satuan: "Kesdam VI/Mlw",
  },
  {
    title: "Rumkit Tk.III dr. Soeharsono Banjarmasin",
    img: "https://i.imgur.com/H7XFliU.jpeg",
    link: "#",
    satuan: "Kesdam VI/Mlw",
  },
  {
    title: "Rumkit Tk.IV Guntung Payung",
    img: "",
    link: "#",
    satuan: "Kesdam VI/Mlw",
  },
  {
    title: "Rumkit Tk.IV awang long Samarinda",
    img: "https://i.imgur.com/WhZ9xpz.jpeg",
    link: "#",
    satuan: "Kesdam VI/Mlw",
  },
  {
    title: "Rumkit Tk.IV Abdul Rais Fatah Tanjung Selor",
    img: "",
    link: "#",
    satuan: "Kesdam VI/Mlw",
  },
  {
    title: "Rumkit Tk.II Udayana, Denpasar",
    img: "https://i.imgur.com/rnH9JYc.jpeg",
    link: "#",
    satuan: "Kesdam IX/Udy",
  },
  {
    title: "Rumkit Tk.III Wira Sakti Kupang",
    img: "https://i.imgur.com/q5STABR.jpeg",
    link: import.meta.env.VITE_WIRA_SAKTI,
    satuan: "Kesdam IX/Udy",
  },
  {
    title: "Rumkit Tk.IV Singaraja",
    img: "https://i.imgur.com/F3FZVvp.jpeg",
    link: "#",
    satuan: "Kesdam IX/Udy",
  },
  {
    title: "Rumkit Tk.IV Wira Bhakti Mataram",
    img: "https://i.imgur.com/dCTl7iX.jpeg",
    link: "#",
    satuan: "Kesdam IX/Udy",
  },
  {
    title: "Rumkit Tk.IV Sultan Abdul Kahir II Bima",
    img: "",
    link: "#",
    satuan: "Kesdam IX/Udy",
  },
  {
    title: "Rumkit Tk.IV 09.07.04 Ignatius Sumantri Atambua",
    img: "",
    link: "#",
    satuan: "Kesdam IX/Udy",
  },
  {
    title: "Rumkit Tk.II Kartika Husada, Pontianak",
    img: "https://i.imgur.com/N6mJK8N.jpeg",
    link: "#",
    satuan: "Kesdam XII/Tpr",
  },
  {
    title: "Rumkit Tk.IV Singkawang",
    img: "https://i.imgur.com/ai4xv1T.jpeg",
    link: import.meta.env.VITE_SINGKAWANG,
    satuan: "Kesdam XII/Tpr",
  },
  {
    title: "Rumkit Tk.IV Sintang",
    img: "",
    link: import.meta.env.VITE_SINTANG,
    satuan: "Kesdam XII/Tpr",
  },
  {
    title: "Rumkit Tk.IV Palangkaraya",
    img: "",
    link: "#",
    satuan: "Kesdam XII/Tpr",
  },
  {
    title: "Rumkit Tk.II RW. Mongisidi, Manado",
    img: "https://i.imgur.com/ARg8O9n.jpeg",
    link: import.meta.env.VITE_MONGINSIDI,
    satuan: "Kesdam XIII/Mdk",
  },
  {
    title: "Rumkit Tk.III dr. Sindhu Trisno, Palu",
    img: sindhu,
    link: import.meta.env.VITE_SINDHU_TRISNO,
    satuan: "Kesdam XIII/Mdk",
  },
  {
    title: "Rumkit Tk.IV dr. Yanto, Sp.OT Poso",
    img: "",
    link: import.meta.env.VITE_YANTO,
    satuan: "Kesdam XIII/Mdk",
  },
  {
    title: "Rumkit Tk.IV dr. Eddy Kounang Gorontalo",
    img: "",
    link: "#",
    satuan: "Kesdam XIII/Mdk",
  },
  {
    title: "Rumkit Tk.II Pelamonia, Makassar",
    img: "https://i.imgur.com/bt6rdeG.jpeg",
    link: import.meta.env.VITE_PELAMONIA,
    satuan: "Kesdam XIV/Hsn",
  },
  {
    title: "Rumkit Tk.IV dr. Soemantri Pare-Pare",
    img: "https://i.imgur.com/6yrm7pO.jpeg",
    link: "",
    satuan: "Kesdam XIV/Hsn",
  },
  {
    title: "Rumkit Tk.IV dr. R. Ismoyo Kendari",
    img: "",
    link: "",
    satuan: "Kesdam XIV/Hsn",
  },
  {
    title: "Rumkit Tk.II Ambon",
    img: "https://i.imgur.com/jZIopBE.jpeg",
    link: import.meta.env.VITE_LATUMETEN,
    satuan: "Kesdam XVI/Ptm",
  },
  {
    title: "Rumkit Tk.II Moh Ridwan Meuraksa",
    img: "https://i.imgur.com/mqMsJ6p.jpeg",
    link: import.meta.env.VITE_RSRIDWAN,
    satuan: "Kesdam Jaya",
  },
  {
    title: "Rumkit Tk.IV Daan Mogot Tangerang",
    img: "",
    link: import.meta.env.VITE_MOGOT,
    satuan: "Kesdam Jaya",
  },
  {
    title: "Rumkit Tk.IV Cijantung",
    img: "",
    link: "",
    satuan: "Kesdam Jaya",
  },
  {
    title: "Rumkit Tk.II Marthen Indey Jayapura",
    img: "",
    link: import.meta.env.VITE_MARTHEN,
    satuan: "Kesdam XVII/Cen",
  },
];
